### ISSUE TITLE
Hosted website seems to not work anymore

### ISSUE THREAD

**Issue by pinage404** [HadrienMP/ensemble-rpg#13]
**Describe the bug**
The website doesn't work

**To Reproduce**
with TLS
1. Go to https://ensemble-rpg.hadrienmp.fr/
2. Observe the error `SSL_ERROR_UNRECOGNIZED_NAME_ALERT`

without secure connection :
1. Go to http://ensemble-rpg.onrender.com
2. Observe the error `Application error` from Heroku

**Expected behavior**
The website should work

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser Firefox
 - Version 111.0.1

**Comment by pinage404** [comment]
This URL seems to work https://ensemble-rpg.onrender.com (after a long loading period)

**Comment by HadrienMP** [comment]
Indeed, the heroku one is down. Render.com is the new one.

**Comment by HadrienMP** [comment]
(Forgot to say I changed the URL on the page)
